### PR TITLE
Added Homebrew support

### PR DESCRIPTION
**Pull request by Dids**
This PR adds initial Homebrew support, which installs the `asimov` binary, as well as configured a launch agent property list, which the user can optionally enable.

If you'd like, I can also attempt to publish the Homebrew Formula to the official Formula repository, although they're somewhat picky on what they'll accept and what they won't, however I personally think it would not only simplify the installation process, but also provide more traction and visibility for Asimov, as it would then show up in search results (`brew search asimov`) for every single Homebrew user.

### CODE REVIEW

**Comment by Dids** [comment]
Sorry, missed https://github.com/stevegrunwell/asimov/issues/2 entirely, so not sure if you'll want to accept this PR or not.

**Comment by stevegrunwell** [comment]
@Dids, thank you for this! Your Homebrew formula is definitely more fleshed out than what I had started in #2, and I was _this_ close to getting it wrapped up before a flight in November.

I'm going to hold on merging just yet until I can verify everything, but if I need to make any adjustments I'll certainly be using this PR branch as a starting point :)

**Comment by ericbf** [comment]
@stevegrunwell any update here? Setting up a new machine and want to see if I can use brew to install this now

**Comment by tverdohleb** [comment]
@stevegrunwell do you have any plans regarding this PR?

**Comment by stevegrunwell** [comment]
Getting into Homebrew is still a priority, but life has this nasty tendency of getting in the way 🙁

Hoping to be able to spend some time on Asimov in the next couple of weeks once things cool down a bit at work.

**Comment by dteirney** [comment]
@stevegrunwell I'd appreciate this PR going in as well. I try to use brew for any binary or app that gets installed and just found this gem of a utility to try and prune down the GB of content that Time Machine tries to backup each night after work.

**Comment by janosh** [comment]
@stevegrunwell bump

**Comment by appinteractive** [comment]
@stevegrunwell any quarantine update on that? Should be ne perfect timing for coding #hoeoffice 
By the way, THANKS for that script, its a lifesaver!

**Review by stevegrunwell — APPROVED** [review]
My sincerest apologies that this has been just hanging in the ether forever, but this is excellent. Thank you so much for your contribution, and I hope you're staying safe throughout ::gestures at current state of the world:: all of this 🙂

**Pull request merged**
